config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "home/index", as: :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blank_game.rb
# frozen_string_literal: true

class BlankGame
  attr_reader :errors

  def initialize
    %i[
      starting_tiles
      gate_tiles
      straight_tiles
      t_tiles
      four_way_tiles
      key_tiles
      keeper_tiles
      wax_eater_tiles
      pit_fiend_tiles
      pathless_tiles
      omen_tiles
    ].each do |attr|
      instance_variable_set("@#{attr}".to_sym, nil)
      class_eval { attr_reader attr }
    end

    @errors = []
  end

  def started?
    false
  end
end

app/models/blank_setup.rb
# frozen_string_literal: true

class BlankSetup
  attr_reader :errors

  def initialize
    %i[
      starting_tiles
      gate_tiles
      straight_tiles
      t_tiles
      four_way_tiles
      key_tiles
      keeper_tiles
      wax_eater_tiles
      pit_fiend_tiles
      pathless_tiles
      omen_tiles
    ].each do |attr|
      instance_variable_set("@#{attr}".to_sym, nil)
      class_eval { attr_reader attr }
    end

    @errors = []
  end

  def ready?
    false
  end
end

app/models/discarded_tiles.rb
# frozen_string_literal: true

class DiscardedTiles
  DEFAULTS = {
    starting_tiles: 0,
    gate_tiles: 0,
    straight_tiles: 0,
    t_tiles: 0,
    four_way_tiles: 0,
    key_tiles: 0,
    keeper_tiles: 0,
    wax_eater_tiles: 0,
    pit_fiend_tiles: 0,
    pathless_tiles: 0,
    omen_tiles: 0
  }.freeze

  def initialize(game:, params:)
    @game = game
    @params = params.present? ? params : DEFAULTS

    @params.each do |key, value|
      instance_variable_set("@#{key}".to_sym, value.to_i)
      class_eval { attr_reader key.to_sym }
    end
  end

  def gameover?
    keys_lost? || gates_lost?
  end

  def gameover_reason
    keys_lost? ? 'keys' : 'gates'
  end

  private

  def gates_lost?
    (@game.gate_tiles - gate_tiles).zero?
  end

  def keys_lost?
    if key_game?
      (@game.key_tiles - key_tiles).zero?
    elsif keeper_game?
      (@game.keeper_tiles - keeper_tiles).zero?
    end
  end

  def key_game?
    @game.key_tiles.positive?
  end

  def keeper_game?
    @game.keeper_tiles.positive?
  end
end

app/models/drawn_tiles.rb
# frozen_string_literal: true

class DrawnTiles
  DEFAULTS = {
    starting_tiles: 0,
    gate_tiles: 0,
    straight_tiles: 0,
    t_tiles: 0,
    four_way_tiles: 0,
    key_tiles: 0,
    keeper_tiles: 0,
    wax_eater_tiles: 0,
    pit_fiend_tiles: 0,
    pathless_tiles: 0,
    omen_tiles: 0,
    discarded_gate_tiles: 0,
    discarded_key_tiles: 0
  }.freeze

  def initialize(setup:, params:)
    @setup = setup
    @params = params.present? ? params : DEFAULTS

    @params.each do |key, value|
      instance_variable_set("@#{key}".to_sym, value.to_i)
      class_eval { attr_reader key.to_sym }
    end
  end

  def gameover?
    keys_lost? || gates_lost?
  end

  def gameover_reason
    keys_lost? ? 'keys' : 'gates'
  end

  private

  def gates_lost?
    (@setup.gate_tiles - discarded_gate_tiles).zero?
  end

  def keys_lost?
    key_count = using_keys? ? :key_tiles : :keeper_tiles

    (@setup.send(key_count) - discarded_key_tiles).zero?
  end

  def using_keys?
    @setup.key_tiles.positive?
  end

  def using_keepers?
    @setup.keeper_tiles.positive?
  end
end

app/models/game.rb
# frozen_string_literal: true

class Game
  attr_reader :errors

  def initialize(params)
    params.each do |key, value|
      instance_variable_set("@#{key}".to_sym, value.to_i)
      class_eval { attr_reader key.to_sym }
    end

    @errors = []
    run_validations unless params.blank?
  end

  def started?
    valid? && starting_tiles.present?
  end

  def to_h
    instance_variables.each_with_object({}) do |ivar, hash|
      next if ivar == :@errors

      key = ivar.to_s.delete_prefix('@').to_sym
      hash[key] = instance_variable_get(ivar)
    end
  end

  private

  def run_validations
    starting_tiles_count
    keys_vs_keepers
    key_count
  end

  def starting_tiles_count
    return if starting_tiles.in? [4, 5]

    @errors << 'You must have 4 or 5 starting tiles.'
  end

  def keys_vs_keepers
    return unless key_tiles.positive? && keeper_tiles.positive?

    @errors << 'You must play with EITHER keys OR keepers, not both.'
  end

  def key_count
    return unless (key_tiles.positive? && key_tiles < 4) || (keeper_tiles.positive? && keeper_tiles < 4)

    @errors << 'You need at least 4 keys/keepers'
  end

  def valid?
    @errors.empty?
  end
end

app/models/game_setup.rb
# frozen_string_literal: true

class GameSetup
  attr_reader :errors

  def initialize(params)
    params.each do |key, value|
      instance_variable_set("@#{key}".to_sym, value.to_i)
      class_eval { attr_reader key.to_sym }
    end

    @errors = []
    run_validations unless params.blank?
  end

  def ready?
    valid? && starting_tiles.present?
  end

  def to_h
    instance_variables.each_with_object({}) do |ivar, hash|
      next if ivar == :@errors

      key = ivar.to_s.delete_prefix('@').to_sym
      hash[key] = instance_variable_get(ivar)
    end
  end

  private

  def run_validations
    starting_tiles_count
    keys_vs_keepers
    key_count
  end

  def starting_tiles_count
    return if starting_tiles.in? [4, 5]

    @errors << 'You must have 4 or 5 starting tiles.'
  end

  def keys_vs_keepers
    return unless key_tiles.positive? && keeper_tiles.positive?

    @errors << 'You must play with EITHER keys OR keepers, not both.'
  end

  def key_count
    return if key_tiles >= 4 || keeper_tiles >= 4

    @errors << 'You need at least 4 keys/keepers'
  end

  def valid?
    @errors.empty?
  end
end

app/models/tile_stats.rb
# frozen_string_literal: true

class TileStats
  def initialize(setup, drawn)
    @setup = setup
    @drawn = drawn
  end

  def to_h
    {
      safe_tiles: safe_tiles,
      safe_tiles_left: safe_tiles_left,
      monster_tiles: monster_tiles,
      monster_tiles_left: monster_tiles_left,
      total_tiles: total,
      total_tiles_left: total_left
    }
  end

  def total_tiles
    safe_tiles + monster_tiles
  end

  def total_tiles_left
    total_tiles - (drawn_safe_tiles + drawn_monster_tiles)
  end

  def safe_tiles
    path_tiles + @setup.key_tiles + @setup.gate_tiles
  end

  def safe_tiles_left
    safe_tiles - drawn_safe_tiles
  end

  def path_tiles
    @setup.starting_tiles + @setup.straight_tiles + @setup.t_tiles + @setup.four_way_tiles
  end

  def path_tiles_left
    path_tiles - drawn_path_tiles
  end

  def monster_tiles
    @setup.keeper_tiles + @setup.wax_eater_tiles + @setup.pit_fiend_tiles +
      @setup.pathless_tiles + @setup.omen_tiles
  end

  def monster_tiles_left
    monster_tiles - drawn_monster_tiles
  end

  def gate_tiles_left
    @setup.gate_tiles - @drawn.gate_tiles
  end

  def key_tiles_left
    key_method = @setup.key_tiles.positive? ? :key_tiles : :keeper_tiles

    @setup.send(key_method) - @drawn.send(key_method)
  end

  def drawn_safe_tiles
    drawn_path_tiles + @drawn.key_tiles + @drawn.gate_tiles
  end

  def drawn_path_tiles
    @drawn.starting_tiles + @drawn.straight_tiles + @drawn.t_tiles +
      @drawn.four_way_tiles
  end

  def drawn_monster_tiles
    @drawn.keeper_tiles + @drawn.wax_eater_tiles +
      @drawn.pit_fiend_tiles + @drawn.pathless_tiles  + @drawn.omen_tiles
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @setup = setup_params.present? ? GameSetup.new(setup_params) : BlankSetup.new
    @drawn = DrawnTiles.new(setup: @setup, params: drawn_params)
    @stats = TileStats.new(@setup, @drawn)
  end

  private

  def setup_params
    params[:setup]
  end

  def drawn_params
    params[:drawn]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_discarded_tiles.html.erb
<div class="mt-3 mb-5">
  <h1 class="text-shadow">
    DISCARDED Tiles (Game Progress)
  </h1>

  <% if @discarded.gameover? %>

    <div class="my-4 alert alert-danger text-center">
      <p>
        Too many <%= @discarded.gameover_reason %> have been lost! Your party is
        swallowed by the crushing darkness.
      </p>

      <b>GAMEOVER</b>
    </div>

    <div>
      <%= link_to 'Reset Game', root_path,
            class: 'btn w-100 btn-danger',
            data: {
              turbo_confirm: 'Are you sure? This will reset to a NEW game',
              turbo_method: :get
            }
      %>
    </div>

  <% else %>

    <%= form_with url: home_path, method: :get do |f| %>
      <% @game.to_h.each do |key, value| %>
        <%= f.hidden_field key, name: "setup[#{key}]", value: value %>
      <% end %>

      <div class="row">
        <div class="col">
          <%= f.label 'Starting', class: 'text-shadow' %>
          <%= f.number_field :starting_tiles,
                name: 'discarded[starting_tiles]',
                class: 'form-control',
                value: @discarded.starting_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col">
          <%= f.label 'Gates', class: 'text-shadow' %>
          <%= f.number_field :gate_tiles,
                name: 'discarded[gate_tiles]',
                class: 'form-control',
                value: @discarded.gate_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col">
          <%= f.label 'Straight', class: 'text-shadow' %>
          <%= f.number_field :straight_tiles,
                name: 'discarded[straight_tiles]',
                class: 'form-control',
                value: @discarded.straight_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col">
          <%= f.label 'T-path', class: 'text-shadow' %>
          <%= f.number_field :t_tiles,
                name: 'discarded[t_tiles]',
                class: 'form-control',
                value: @discarded.t_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col">
          <%= f.label 'Four-Way', class: 'text-shadow' %>
          <%= f.number_field :four_way_tiles,
                name: 'discarded[four_way_tiles]',
                class: 'form-control',
                value: @discarded.four_way_tiles || 0,
                min: 0
          %>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col-3">
          <%= f.label 'Keys', class: 'text-shadow' %>
          <%= f.number_field :key_tiles,
                name: 'discarded[key_tiles]',
                class: 'form-control',
                value: @discarded.key_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col-1 text-center">
          <div class="invisible">.</div>
          <div>or</div>
        </div>

        <div class="col-3">
          <%= f.label 'Keepers', class: 'text-shadow' %>
          <%= f.number_field :keeper_tiles,
                name: 'discarded[keeper_tiles]',
                class: 'form-control',
                value: @discarded.keeper_tiles || 0,
                min: 0
          %>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col">
          <%= f.label 'Wax Eaters', class: 'text-shadow' %>
          <%= f.number_field :wax_eater_tiles,
                name: 'discarded[wax_eater_tiles]',
                class: 'form-control',
                value: @discarded.wax_eater_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col">
          <%= f.label 'Pit Fiends', class: 'text-shadow' %>
          <%= f.number_field :pit_fiend_tiles,
                name: 'discarded[pit_fiend_tiles]',
                class: 'form-control',
                value: @discarded.pit_fiend_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col">
          <%= f.label 'Pathless', class: 'text-shadow' %>
          <%= f.number_field :pathless_tiles,
                name: 'discarded[pathless_tiles]',
                class: 'form-control',
                value: @discarded.pathless_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col">
          <%= f.label 'Omens', class: 'text-shadow' %>
          <%= f.number_field :omen_tiles,
                name: 'discarded[omen_tiles]',
                class: 'form-control',
                value: @discarded.omen_tiles || 0,
                min: 0
          %>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col">
          <%= f.submit 'Save', class: 'btn btn-primary btn-lg w-100' %>
        </div>
      </div>

    <% end %>

  <% end %>
</div>

app/views/home/_drawn_tiles.html.erb
<div class="mt-3 mb-5">
  <h1 class="text-shadow">
    DRAWN Tiles (Game Progress)
  </h1>

  <% if @drawn.gameover? %>

    <div class="my-4 alert alert-danger text-center">
      <p>
        Too many <%= @drawn.gameover_reason %> have been lost! Your party is
        swallowed by the crushing darkness.
      </p>

      <b>GAMEOVER</b>
    </div>

    <div>
      <%= link_to 'Reset Game', root_path,
            class: 'btn w-100 btn-danger',
            data: {
              turbo_confirm: 'Are you sure? This will reset to a NEW game',
              turbo_method: :get
            }
      %>
    </div>

  <% else %>

    <%= form_with url: home_path, method: :get do |f| %>
      <% @setup.to_h.each do |key, value| %>
        <%= f.hidden_field key, name: "setup[#{key}]", value: value %>
      <% end %>

      <div class="row">
        <div class="col">
          <%= f.label 'Starting', class: 'text-shadow' %>
          <%= f.number_field :starting_tiles,
                name: 'drawn[starting_tiles]',
                class: 'form-control',
                value: @drawn.starting_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col">
          <%= f.label 'Gates', class: 'text-shadow' %>
          <%= f.number_field :gate_tiles,
                name: 'drawn[gate_tiles]',
                class: 'form-control',
                value: @drawn.gate_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col">
          <%= f.label 'Straight', class: 'text-shadow' %>
          <%= f.number_field :straight_tiles,
                name: 'drawn[straight_tiles]',
                class: 'form-control',
                value: @drawn.straight_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col">
          <%= f.label 'T-path', class: 'text-shadow' %>
          <%= f.number_field :t_tiles,
                name: 'drawn[t_tiles]',
                class: 'form-control',
                value: @drawn.t_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col">
          <%= f.label 'Four-Way', class: 'text-shadow' %>
          <%= f.number_field :four_way_tiles,
                name: 'drawn[four_way_tiles]',
                class: 'form-control',
                value: @drawn.four_way_tiles || 0,
                min: 0
          %>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col-3">
          <%= f.label 'Keys', class: 'text-shadow' %>
          <%= f.number_field :key_tiles,
                name: 'drawn[key_tiles]',
                class: 'form-control',
                value: @drawn.key_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col-1 text-center">
          <div class="invisible">.</div>
          <div class="text-shadow">or</div>
        </div>

        <div class="col-3">
          <%= f.label 'Keepers', class: 'text-shadow' %>
          <%= f.number_field :keeper_tiles,
                name: 'drawn[keeper_tiles]',
                class: 'form-control',
                value: @drawn.keeper_tiles || 0,
                min: 0
          %>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col">
          <%= f.label 'Wax Eaters', class: 'text-shadow' %>
          <%= f.number_field :wax_eater_tiles,
                name: 'drawn[wax_eater_tiles]',
                class: 'form-control',
                value: @drawn.wax_eater_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col">
          <%= f.label 'Pit Fiends', class: 'text-shadow' %>
          <%= f.number_field :pit_fiend_tiles,
                name: 'drawn[pit_fiend_tiles]',
                class: 'form-control',
                value: @drawn.pit_fiend_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col">
          <%= f.label 'Pathless', class: 'text-shadow' %>
          <%= f.number_field :pathless_tiles,
                name: 'drawn[pathless_tiles]',
                class: 'form-control',
                value: @drawn.pathless_tiles || 0,
                min: 0
          %>
        </div>

        <div class="col">
          <%= f.label 'Omens', class: 'text-shadow' %>
          <%= f.number_field :omen_tiles,
                name: 'drawn[omen_tiles]',
                class: 'form-control',
                value: @drawn.omen_tiles || 0,
                min: 0
          %>
        </div>
      </div>

      <div class="row mt-5">
        <div class="col-5">
          <div class="row">
            <h3 class="text-shadow">LOST</h3>
            <div class="col">
              <%= f.label 'Gates', class: 'text-shadow' %>
              <%= f.number_field :discarded_gate_tiles,
                    name: 'drawn[discarded_gate_tiles]',
                    class: 'form-control',
                    value: @drawn.discarded_gate_tiles || 0,
                    min: 0
              %>
            </div>
            <div class="col">
              <%= f.label 'Keys', class: 'text-shadow' %>
              <%= f.number_field :discarded_key_tiles,
                    name: 'drawn[discarded_key_tiles]',
                    class: 'form-control',
                    value: @drawn.discarded_key_tiles || 0,
                    min: 0
              %>
            </div>
          </div>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col">
          <%= f.submit 'Record', class: 'btn btn-primary btn-lg w-100' %>
        </div>
      </div>

    <% end %>

  <% end %>
</div>

app/views/home/_game_tiles.html.erb
<% if @game.errors.any? %>
  <% @game.errors.each do |error| %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <div><%= error %></div>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

<h2>Game Setup</h2>

<%= form_with url: home_path, method: :get do |f| %>
  <div class="row">
    <b>Base Tiles</b>

    <div class="col">
      <%= f.label 'Starting' %>
      <%= f.number_field :starting_tiles,
            name: 'setup[starting_tiles]',
            class: 'form-control',
            value: @game.starting_tiles || 4,
            min: 4,
            max: 5
      %>
    </div>

    <div class="col">
      <%= f.label 'Gates' %>
      <%= f.number_field :gate_tiles,
            name: 'setup[gate_tiles]',
            class: 'form-control',
            value: @game.gate_tiles || 4,
            readonly: true,
            style: "background-color: #e9ecef; opacity: 1;"
      %>
    </div>

    <div class="col">
      <%= f.label 'Straight' %>
      <%= f.number_field :straight_tiles,
            name: 'setup[straight_tiles]',
            class: 'form-control',
            value: @game.straight_tiles || 10
      %>
    </div>

    <div class="col">
      <%= f.label 'T-intersection' %>
      <%= f.number_field :t_tiles,
            name: 'setup[t_tiles]',
            class: 'form-control',
            value: @game.t_tiles || 32
      %>
    </div>

    <div class="col">
      <%= f.label 'Four-Way' %>
      <%= f.number_field :four_way_tiles,
            name: 'setup[four_way_tiles]',
            class: 'form-control',
            value: @game.four_way_tiles || 12
      %>
    </div>
  </div>

  <div class="row mt-3">
    <b>Key Tiles</b>

    <div class="col">
      <%= f.label 'Keys' %>
      <%= f.number_field :key_tiles,
            name: 'setup[key_tiles]',
            class: 'form-control',
            value: @game.key_tiles || 6,
            max: 8
      %>
    </div>

    <div class="col text-center">
      <div class="invisible">.</div>
      <div>or</div>
    </div>

    <div class="col">
      <%= f.label 'Keepers' %>
      <%= f.number_field :keeper_tiles,
            name: 'setup[keeper_tiles]',
            class: 'form-control',
            value: @game.keeper_tiles || 0,
            max: 8
      %>
    </div>
  </div>

  <div class="row mt-3">
    <b>Monster Tiles</b>

    <div class="col">
      <%= f.label 'Wax Eaters' %>
      <%= f.number_field :wax_eater_tiles,
            name: 'setup[wax_eater_tiles]',
            class: 'form-control',
            value: @game.wax_eater_tiles || 13
      %>
    </div>

    <div class="col">
      <%= f.label 'Pit Fiends' %>
      <%= f.number_field :pit_fiend_tiles,
            name: 'setup[pit_fiend_tiles]',
            class: 'form-control',
            value: @game.pit_fiend_tiles || 2,
            max: 3
      %>
    </div>

    <div class="col">
      <%= f.label 'Pathless' %>
      <%= f.number_field :pathless_tiles,
            name: 'setup[pathless_tiles]',
            class: 'form-control',
            value: @game.pathless_tiles || 2,
            max: 3
      %>
    </div>

    <div class="col">
      <%= f.label 'Omens (summon the Dirge)' %>
      <%= f.number_field :omen_tiles,
            name: 'setup[omen_tiles]',
            class: 'form-control',
            value: @game.omen_tiles || 2,
            max: 5
      %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">
      <%= f.submit 'Save', class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

app/views/home/_index.html.erb
<%= turbo_frame_tag :home, data: {turbo_action: :advance} do %>
  <div class="container mt-3">
    <% if setup.ready? %>

      <%= render 'drawn_tiles', setup: setup, drawn: drawn %>
      <%= render 'stats', stats: stats %>

    <% else %>

      <%= render 'setup', setup: setup %>

    <% end %>
  </div>
<% end %>

app/views/home/_setup.html.erb
<% if @setup.errors.any? %>
  <% @setup.errors.each do |error| %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <div><%= error %></div>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

<h1 class="text-shadow">
  Game Setup
</h1>

<%= form_with url: home_path, method: :get do |f| %>
  <div class="row">
    <b class="text-shadow">Path Tiles</b>

    <div class="col">
      <%= f.label 'Starting', class: 'text-shadow' %>
      <%= f.number_field :starting_tiles,
            name: 'setup[starting_tiles]',
            class: 'form-control',
            value: @setup.starting_tiles || 4,
            min: 4,
            max: 5
      %>
    </div>

    <div class="col">
      <%= f.label 'Gates', class: 'text-shadow' %>
      <%= f.number_field :gate_tiles,
            name: 'setup[gate_tiles]',
            class: 'form-control',
            value: @setup.gate_tiles || 4,
            readonly: true,
            style: "background-color: #e9ecef; opacity: 1;"
      %>
    </div>

    <div class="col">
      <%= f.label 'Straight', class: 'text-shadow' %>
      <%= f.number_field :straight_tiles,
            name: 'setup[straight_tiles]',
            class: 'form-control',
            value: @setup.straight_tiles || 10
      %>
    </div>

    <div class="col">
      <%= f.label 'T-intersection', class: 'text-shadow' %>
      <%= f.number_field :t_tiles,
            name: 'setup[t_tiles]',
            class: 'form-control',
            value: @setup.t_tiles || 32
      %>
    </div>

    <div class="col">
      <%= f.label 'Four-Way', class: 'text-shadow' %>
      <%= f.number_field :four_way_tiles,
            name: 'setup[four_way_tiles]',
            class: 'form-control',
            value: @setup.four_way_tiles || 12
      %>
    </div>
  </div>

  <div class="row mt-3">
    <b>Key Tiles</b>

    <div class="col-3">
      <%= f.label 'Keys', class: 'text-shadow' %>
      <%= f.number_field :key_tiles,
            name: 'setup[key_tiles]',
            class: 'form-control',
            value: @setup.key_tiles || 6,
            max: 8,
            min: 0
      %>
    </div>

    <div class="col-1 text-center">
      <div class="invisible">.</div>
      <div class="text-shadow">or</div>
    </div>

    <div class="col-3">
      <%= f.label 'Keepers', class: 'text-shadow' %>
      <%= f.number_field :keeper_tiles,
            name: 'setup[keeper_tiles]',
            class: 'form-control',
            value: @setup.keeper_tiles || 0,
            max: 8,
            min: 0
      %>
    </div>
  </div>

  <div class="row mt-3">
    <b class="text-shadow">Monster Tiles</b>

    <div class="col">
      <%= f.label 'Wax Eaters', class: 'text-shadow' %>
      <%= f.number_field :wax_eater_tiles,
            name: 'setup[wax_eater_tiles]',
            class: 'form-control',
            value: @setup.wax_eater_tiles || 13
      %>
    </div>

    <div class="col">
      <%= f.label 'Pit Fiends', class: 'text-shadow' %>
      <%= f.number_field :pit_fiend_tiles,
            name: 'setup[pit_fiend_tiles]',
            class: 'form-control',
            value: @setup.pit_fiend_tiles || 2,
            max: 3
      %>
    </div>

    <div class="col">
      <%= f.label 'Pathless', class: 'text-shadow' %>
      <%= f.number_field :pathless_tiles,
            name: 'setup[pathless_tiles]',
            class: 'form-control',
            value: @setup.pathless_tiles || 2,
            max: 3
      %>
    </div>

    <div class="col">
      <%= f.label 'Omens', class: 'text-shadow' %>
      <%= f.number_field :omen_tiles,
            name: 'setup[omen_tiles]',
            class: 'form-control',
            value: @setup.omen_tiles || 2,
            max: 5
      %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">
      <%= f.submit 'Begin', class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="container mt-3">
  <% if @setup.ready? %>

    <%= render 'drawn_tiles' %>
    <%= render 'stats' %>

  <% else %>

    <%= render 'setup_tiles' %>

  <% end %>
</div>

app/views/home/index.turbo_stream.erb
<%= turbo_stream.replace :home do %>
  <%= render 'home/index', setup: @setup, drawn: @drawn, stats: @stats %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NightCage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-black text-light">
    <%= render 'shared/navbar' %>

    <%= yield %>
  </body>
</html>